// <auto-generated />
using System;
using LabsQueueBot.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabsQueueBot.DataAccess.Migrations
{
    [DbContext(typeof(QueueBotContext))]
    [Migration("20250920175802_Update_UsersTable_LastCallbackableMessageId_Migration")]
    partial class Update_UsersTable_LastCallbackableMessageId_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabsQueueBot.DataAccess.Entities.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QueueIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<long>("TgUserIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SerialNumberRepository");
                });

            modelBuilder.Entity("LabsQueueBot.DataAccess.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("CourseNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("EvenWeekTimetable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("GroupNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("OddWeekTimetable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long[]>("Queue")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long[]>("Waiting")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("Id");

                    b.HasIndex("CourseNumber", "GroupNumber", "SubjectName")
                        .IsUnique();

                    b.ToTable("SubjectRepository");
                });

            modelBuilder.Entity("LabsQueueBot.DataAccess.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("CourseNumber")
                        .HasColumnType("smallint");

                    b.Property<byte>("GroupNumber")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsNotifyNeeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastCallbackableMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserRepository");
                });

            modelBuilder.Entity("LabsQueueBot.DataAccess.Entities.SerialNumber", b =>
                {
                    b.HasOne("LabsQueueBot.DataAccess.Entities.Subject", "Subject")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LabsQueueBot.DataAccess.Entities.Subject", b =>
                {
                    b.Navigation("SerialNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
