// <auto-generated />
using LabsQueueBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabsQueueBot.Migrations
{
    [DbContext(typeof(QueueBotContext))]
    [Migration("20240926184220_AddSerialNumberTable")]
    partial class AddSerialNumberTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabsQueueBot.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<long>("UserIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SerialNumberRepository");
                });

            modelBuilder.Entity("LabsQueueBot.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("CourseNumber")
                        .HasColumnType("smallint");

                    b.Property<byte>("GroupNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubjectRepository");
                });

            modelBuilder.Entity("LabsQueueBot.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("CourseNumber")
                        .HasColumnType("smallint");

                    b.Property<byte>("GroupNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserRepository");
                });

            modelBuilder.Entity("LabsQueueBot.SerialNumber", b =>
                {
                    b.HasOne("LabsQueueBot.Subject", "Subject")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LabsQueueBot.Subject", b =>
                {
                    b.Navigation("SerialNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
